### ISSUE TITLE
prerequisites

### ISSUE THREAD

**Issue by Tanguyfockedey** [MaaxIT/42_slot_watcher#1]
Nice project,

Would be great to have some note about dependencies.
On the school's computers, node JS and axios is not installed by default. 
I had never heard about axios, and some ppl might just skip when errors about unknown files occur.

**Comment by wasied** [comment]
Hey, thanks for the feedback!

You can install npm/nodejs from homebrew on the school's computers and then install the dependencies from it.
But you're right, I should explain it directly in the README.

I'm doing it rn! 😄

**Comment by wasied** [comment]
Done with [#32e7739](https://github.com/MaaxIT/42_slot_watcher/commit/32e773984c99eed7fe16855d8e15e269dbaf35b4).
Let me know if that's good for you with this update!

**Comment by Tanguyfockedey** [comment]
Sure, well done ;)

**Comment by Tanguyfockedey** [comment]
Is axios included when you install it your way ? 
I had to do "npm install axios"
but I didn't install it all through homebrew.

**Comment by wasied** [comment]
axios should be installed when doing the **npm i** command since it is in the package.json dependencies.

**Comment by Tanguyfockedey** [comment]
ok, dunno what happened on my side, when doing node . it gave an error so I installed axios separately but nvm :p
